### ISSUE TITLE
Chrome doesn't work with the initial JS routine

### ISSUE THREAD

**Issue by okopnik** [t3nsor/quora-backup#13]
Pasting the JS function into the Chrome console results in the following errors:

```
Uncaught ReferenceError: $ is not defined
    at <anonymous>:1:70
window.open().document.write(JSON.stringify(Array.prototype.map.call($('.UserContentList .pagedlist_item'), function (e) { return [$(e).find('a')[0].href, $(e).find('.metadata').text()] })))
VM263:1 Uncaught TypeError: Array.prototype.map called on null or undefined
    at map (native)
    at <anonymous>:1:65
(anonymous) @ VM263:1
main-thumb-33627499-25-jhhwtnwmpleskklqhoepgdoyodyclyqv.jpeg:1 GET https://qph.ec.quoracdn.net/main-thumb-33627499-25-jhhwtnwmpleskklqhoepgdoyodyclyqv.jpeg 403 (Forbidden)
```

Using Chrome version 55.0.2883.95 (64-bit) / Mac.

**Comment by opoudjis** [comment]
My workaround:

javascript:window.open().document.write(JSON.stringify(Array.prototype.map.call(document.querySelectorAll('.UserContentList .pagedlist_item'), function (e) { return [e.getElementsByTagName('a')[0].href, e.getElementsByClassName('metadata')[0].innerHTML] })))

**Comment by okopnik** [comment]
@opoudjis : Well, that got me a month's worth of answers (today is 3/18, the last one in the returned array was from 2/18.) So, still no joy.

This is why I came up with my own solution a while back; it requires manually scrolling down to the bottom of your profile page (a friend we have in common simply put a book on the space bar :), saving it as "Web page, complete", and sending me just the HTML. A few minutes later, all your posts are in the can... or at least in my DB, as well as in an unadvertised, somewhat Quora-looking section of my website (and I'm always happy to send a DB dump to anyone who asks me to do this for them.)

Not very portable, but works without a hitch.

**Comment by opoudjis** [comment]
Oh, I gave up in time for the 1000 answers I needed; but the combo of workaround javascript and "book on space bar" *should* retrieve the whole thing. I've just got it working with blog posts too.

The original Javascript worked fine 6 months ago, and no longer works on either Chrome or Safari. is there a jQuery dependency that's now missing?

**Comment by okopnik** [comment]
Hmm, all looks like bone-standard JS to me.

I do, however, recall reading on StackOverflow - back around the time that I submitted this bug - that a number of browsers have disabled scroll-to-bottom on pages that progressively loaded the content... some security-related argument that I don't remember. Anyway, if you want yours saved, let me know: I'm zonker@gmx.com. Cheers!

**Comment by opoudjis** [comment]
Hang on. You're that guy!

My workaround worked, so I'm good, thanks! But as you'll see from my other issues raised, Quora's UX redesigns seem to have broken a few things.

**Comment by okopnik** [comment]
> Hang on. You're that guy!

Why, yes - it seems a number of people think that's my name. :)

> But as you'll see from my other issues raised, Quora's UX redesigns seem to have broken a few things.

Yep, that's why my solution relies more on rather loose regexes. They're always tweaking the UX; trying to achieve maximum user resentment, from what I can tell...

Good to know this worked for you, though. Cheers!

**Comment by t3nsor** [comment]
Fixed by https://github.com/t3nsor/quora-backup/commit/a2b5750b1c1d057908640c6777f4e5badaad56d0
