### ISSUE TITLE
Anonymous answers generate non-ASCII character

### ISSUE THREAD

**Issue by opoudjis** [t3nsor/quora-backup#14]
The metadata element of an anonymous answer, as fetched in the Javascript fetching all timestamps of answers, looks like:

"Anonymous · Added Mar 1"

That middle dot is non Ascii, and makes crawler.py barf at     `answers = json.load(input_file)`

You might want to put some filtering out of non-Ascii characters from the loaded JSON in to preempt that. The middle dot can straightforwardly be replaced with a period.

**Comment by t3nsor** [comment]
I could not reproduce this issue, but, after reading the documentation, I could see how Python's handling of text files could be an issue. https://github.com/t3nsor/quora-backup/commit/c687b957ddf3bb626fd9c195f1346dee4c09f2ce should fix this, unless you managed to save the JSON as not UTF-8 in the first place (don't do that).
