### ISSUE TITLE
HTML content has changed, removing critical style from converter.py

### ISSUE THREAD

**Issue by opoudjis** [t3nsor/quora-backup#15]
Styles have changed: in particular the node with QuestionArea has been removed:

`<div class="CenteredQuestionPage NewGridQuestionPage QuestionAnswerPageMain"><div class="grid_page"><div class="layout_centered_2col_main"><div class="ans_page_question_header"><div id="MVzBgP"><div class="QuestionArea"><div id="VoNHyN
"><div class="question_text_edit"><h1><span id="RymIQB"><a class="question_link" href="/What-is-the-etymology-of-Gylippus-It-has-to-do-with-h
orses-but-what-else" action_mousedown="QuestionLinkClickthrough" id="__w2_QKath9N_link">`

is now:

`<div class='CenteredQuestionPage NewGridQu
estionPage QuestionAnswerPageMain'><div class='grid_page'><div class='layout_centered_2col_main'><div class='ans_page_question_header'><div c
lass='_type_serif_title_xlarge pass_color_to_child_links'><div id='GgjOTP'><a class='question_link' href='/What-is-the-etymology-of-Gylippus-
It-has-to-do-with-horses-but-what-else' target='_top' action_mousedown='QuestionLinkClickthrough' id='__w2_z5KqY6h_link'>`

As a result, converter.py cannot function: QuestionArea is no longer the class to look for.

**Comment by opoudjis** [comment]
Have modified to look for ans_page_question_header instead of QuestionArea

**Comment by t3nsor** [comment]
can't reproduce - they must have changed it back or something
