### ISSUE TITLE
Javascript execution on browser create an empty page.

### ISSUE THREAD

**Issue by jaympatel1893** [t3nsor/quora-backup#2]
I tried execution of the javascript on console of two browsers: Mozilla and Chrome. 
It opens a new tab with blank screens.

What is the issue?

**Comment by t3nsor** [comment]
That's hard to say without more information. Does the console show any errors?

**Comment by jaympatel1893** [comment]
Is it because I am using Windows?
Console error is :
TypeError: Array.prototype.map called on null or undefined

Any guidelines to achive this in windows?

**Comment by t3nsor** [comment]
JavaScript should work the same on Windows. What does `$('.UserContentList .pagedlist_item')` return in the console for you?

**Comment by skrishnan22** [comment]
Changing $('.UserContentList .pagedlist_item') to $('.AnswerListItem.PagedListItem.feed_item') worked for me,but the time stamp was empty.

**Comment by t3nsor** [comment]
Still can't reproduce, so closing.
