### ISSUE TITLE
Date parsing case missed

### ISSUE THREAD

**Issue by ashish1294** [t3nsor/quora-backup#4]
Quora answers may have strings like "Added 12am" - and the script fails to parse such string - giving me xxxx-xx-xx. Just need to add another regex. Should be easy to fix.

**Comment by t3nsor** [comment]
Have you checked that it only shows "12am" and never any other hour?

**Comment by ashish1294** [comment]
Yesh. I did some testing manually. It shows only 12am.

**Comment by ashish1294** [comment]
There's one more thing. For answers that were not written in the current year,
Quora shows something like - "Added 12 Nov 2014". However, the script assumes "Added 12 Nov, 2014" (Notice the extra comma).

I think Quora might have changed this format after this script was written.

**Comment by ashish1294** [comment]
I just checked again - It may show any hour. Will fix this.

**Comment by t3nsor** [comment]
Thanks!
